In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Lenovo\Desktop\Design_Applications\Resume dataset.csv")

,category,job_title,Text
0,Java Developers/Architects Resumes,Java Developer,Flair for technology and willing to take chall...
1,Java Developers/Architects Resumes,Sr. Java/J2EE Developer,Senior Java Developer with around 7+ years of ...
2,Java Developers/Architects Resumes,Sr. iOS Developer,Overall 7 years of experience in design and de...
3,Java Developers/Architects Resumes,Core Java Developer,7 + years of experience in Application Analysi...
4,Java Developers/Architects Resumes,Android Developer,With approx 5 years of experience in IT sector...
...,...,...,...
8995,Recruiter Resumes,IOS Developer,7+ years of experience in designing & developi...
8996,Recruiter Resumes,UI,8 years of experience in User Interface Design...
8997,Recruiter Resumes,Web Application Developer,Skilled IT Professional with proven success in...
8998,Recruiter Resumes,IOS Developer,"Over seven (7+) years of total IT experience, ..."
8999,Recruiter Resumes,Android Developer,8 Years of IT experience with Over 5 years of ...

,category,job_title,Text
0,Java Developers/Architects Resumes,Java Developer,Flair for technology and willing to take chall...
1,Java Developers/Architects Resumes,Sr. Java/J2EE Developer,Senior Java Developer with around 7+ years of ...
2,Java Developers/Architects Resumes,Sr. iOS Developer,Overall 7 years of experience in design and de...
3,Java Developers/Architects Resumes,Core Java Developer,7 + years of experience in Application Analysi...
4,Java Developers/Architects Resumes,Android Developer,With approx 5 years of experience in IT sector...
...,...,...,...
8993,Recruiter Resumes,AWS/DevOps Engineer,: 8 years of professional experience in DevOps...
8994,Recruiter Resumes,Java Developer,Over 8+ years of extensive IT experience in de...
8996,Recruiter Resumes,UI,8 years of experience in User Interface Design...
8997,Recruiter Resumes,Web Application Developer,Skilled IT Professional with proven success in...
8998,Recruiter Resumes,IOS Developer,"Over seven (7+) years of total IT experience, ..."

In [4]:
print(df['category'].value_counts())

category
Java Developers/Architects Resumes                1000
Web Developer Resumes                             1000
SQL Developers Resumes                            1000
Business Analyst (BA) Resumes                     1000
Network and Systems Administrators Resumes        1000
Datawarehousing, ETL, Informatica Resumes         1000
Business Intelligence, Business Object Resumes    1000
Project Manager Resumes                           1000
Recruiter Resumes                                 1000
Name: count, dtype: int64

In [25]:
java_dev_df = df[df['category'] ==  'Java Developers/Architects Resumes'].copy()
java_resume_df = java_dev_df[java_dev_df['job_title'] == 'Java Developer'].copy()

java_resume_df.drop_duplicates()

,category,job_title,Text
0,Java Developers/Architects Resumes,Java Developer,Flair for technology and willing to take chall...
18,Java Developers/Architects Resumes,Java Developer,7+ years of professional experience in Analysi...
20,Java Developers/Architects Resumes,Java Developer,5 years of experience in developing Web based ...
37,Java Developers/Architects Resumes,Java Developer,Over 7+ years of experience in Object Oriented...
43,Java Developers/Architects Resumes,Java Developer,Over 7 years of IT industry experience in Arch...
...,...,...,...
930,Java Developers/Architects Resumes,Java Developer,"Over Six years of IT experience in analysis, d..."
937,Java Developers/Architects Resumes,Java Developer,"Over 7+ years of experience in designing, impl..."
949,Java Developers/Architects Resumes,Java Developer,Around 8 years of Outstanding Java Development...
967,Java Developers/Architects Resumes,Java Developer,Around 8+ years IT experience including Strong...
981,Java Developers/Architects Resumes,Java Developer,Java Programmer with over 6 years of IT experi...

In [32]:
long_resumes = java_resume_df[java_resume_df['Text'].str.len() > 600]
final_resumes = long_resumes.drop_duplicates()
final_resumes

,category,job_title,Text
0,Java Developers/Architects Resumes,Java Developer,Flair for technology and willing to take chall...
18,Java Developers/Architects Resumes,Java Developer,7+ years of professional experience in Analysi...
20,Java Developers/Architects Resumes,Java Developer,5 years of experience in developing Web based ...
37,Java Developers/Architects Resumes,Java Developer,Over 7+ years of experience in Object Oriented...
43,Java Developers/Architects Resumes,Java Developer,Over 7 years of IT industry experience in Arch...
...,...,...,...
930,Java Developers/Architects Resumes,Java Developer,"Over Six years of IT experience in analysis, d..."
937,Java Developers/Architects Resumes,Java Developer,"Over 7+ years of experience in designing, impl..."
949,Java Developers/Architects Resumes,Java Developer,Around 8 years of Outstanding Java Development...
967,Java Developers/Architects Resumes,Java Developer,Around 8+ years IT experience including Strong...
981,Java Developers/Architects Resumes,Java Developer,Java Programmer with over 6 years of IT experi...

In [38]:
selected_50 = final_resumes.sample(n=50, random_state=42).reset_index(drop=True)
selected_50

                              category       job_title  \
0   Java Developers/Architects Resumes  Java Developer
1   Java Developers/Architects Resumes  Java Developer
2   Java Developers/Architects Resumes  Java Developer
3   Java Developers/Architects Resumes  Java Developer
4   Java Developers/Architects Resumes  Java Developer
5   Java Developers/Architects Resumes  Java Developer
6   Java Developers/Architects Resumes  Java Developer
7   Java Developers/Architects Resumes  Java Developer
8   Java Developers/Architects Resumes  Java Developer
9   Java Developers/Architects Resumes  Java Developer
10  Java Developers/Architects Resumes  Java Developer
11  Java Developers/Architects Resumes  Java Developer
12  Java Developers/Architects Resumes  Java Developer
13  Java Developers/Architects Resumes  Java Developer
14  Java Developers/Architects Resumes  Java Developer
15  Java Developers/Architects Resumes  Java Developer
16  Java Developers/Architects Resumes  Java Developer
17  Java Developers/Architects Resumes  Java Developer
18  Java Developers/Architects Resumes  Java Developer
19  Java Developers/Architects Resumes  Java Developer
20  Java Developers/Architects Resumes  Java Developer
21  Java Developers/Architects Resumes  Java Developer
22  Java Developers/Architects Resumes  Java Developer
23  Java Developers/Architects Resumes  Java Developer
24  Java Developers/Architects Resumes  Java Developer
25  Java Developers/Architects Resumes  Java Developer
26  Java Developers/Architects Resumes  Java Developer
27  Java Developers/Architects Resumes  Java Developer
28  Java Developers/Architects Resumes  Java Developer
29  Java Developers/Architects Resumes  Java Developer
30  Java Developers/Architects Resumes  Java Developer
31  Java Developers/Architects Resumes  Java Developer
32  Java Developers/Architects Resumes  Java Developer
33  Java Developers/Architects Resumes  Java Developer
34  Java Developers/Architects Resumes  Java Developer
35  Java Developers/Architects Resumes  Java Developer
36  Java Developers/Architects Resumes  Java Developer
37  Java Developers/Architects Resumes  Java Developer
38  Java Developers/Architects Resumes  Java Developer
39  Java Developers/Architects Resumes  Java Developer
40  Java Developers/Architects Resumes  Java Developer
41  Java Developers/Architects Resumes  Java Developer
42  Java Developers/Architects Resumes  Java Developer
43  Java Developers/Architects Resumes  Java Developer
44  Java Developers/Architects Resumes  Java Developer
45  Java Developers/Architects Resumes  Java Developer
46  Java Developers/Architects Resumes  Java Developer
47  Java Developers/Architects Resumes  Java Developer
48  Java Developers/Architects Resumes  Java Developer
49  Java Developers/Architects Resumes  Java Developer


In [34]:
selected_50.to_csv('final_java_resumes_50.csv', index=False)